### ISSUE TITLE
Feature Request: Player images

### ISSUE THREAD

**Issue by LukasW1337** [Thiry1/csgo-custom-hud#21]
![bd78d9e82313d1c55bcd203fb5251aee](https://user-images.githubusercontent.com/33436545/39153938-f0972c1e-474c-11e8-8f5f-1d3e2f32b759.jpg)

Can we get an image for players like this? That would be really awesome!

**Comment by Thiry1** [comment]
implemented via c1d21af044bafdd02039c411b9e2d64425c82285 .
NOTE: You MUST set player image source to all players.

**Comment by nppb** [comment]
I recently tried this feature, thanks for implementing it (I didn't think I would like it that much!). 
I would suggest some ideas regardless. So at the moment the player picture will look like this:
![player_profile1](https://user-images.githubusercontent.com/37812438/40279231-fe574bac-5c3e-11e8-92b3-c4425d6fc3ab.png)
The picture needs a solid background and emulates the original webcam-style positioning. So if you switch to a player without picture the info bar will move ( I guess that's why you noted that every player needs an image).

First, I would suggest to add the option in playerInfo.ts to declare a default player image, like so:
![player_profile2](https://user-images.githubusercontent.com/37812438/40279246-6eaf27e4-5c3f-11e8-8b91-0f6efaeb5afa.png)
So whenever there is a player being spectated whose Steam-ID is not listed in playerInfo.ts he will get the default picture (But only if the user has specified a default picture).

In general, I would suggest, tho, to change the way this feature is placed since this is a picture and not a webcam. Maybe positioning for player pictures like the following might improve the look a little bit:

![player_profile3](https://user-images.githubusercontent.com/37812438/40279277-f23ed69a-5c3f-11e8-8953-70ea6f0a76b6.png)

Even if this would only be optional to set (like playerPicTopPos="true" or something) I think it might get used quite a lot.

Thank you a lot for the effort you put in this project, I really appreciate your work.

**Comment by Thiry1** [comment]
@nppb 
Thank you for suggestion.

> I guess that's why you noted that every player needs an image

Correct. And I know this is not good for usability. So I will implement what your suggestion (default picture).

>positioning for player pictures like the following might improve the look a little bit

Good idea.Also I will implement this 😄
