### ISSUE TITLE
npm start - app run but show nothing

### ISSUE THREAD

**Issue by benten2411** [Thiry1/csgo-custom-hud#28]
![untitled](https://user-images.githubusercontent.com/37974243/40572378-39a9a9b2-60d5-11e8-914b-8c2401d7bfae.png)

**Comment by nppb** [comment]
I've run into this when changing /src/config/teamInfo.ts and especially referencing wrong file names (for example team logos). Watch out for special characters or missing quotation marks ( " ) in names too.
Make sure to use a fresh install and do not force-close "npm i" or "npm run build", you have to be patient here because these may take a minute or two.

Apart from that you offered very little information so you'd need to give more details on your config.

**Comment by benten2411** [comment]
![image](https://user-images.githubusercontent.com/37974243/40575628-941e0dd8-6112-11e8-8a3d-e6c389f428cc.png)
this is what happened after i add name + logo

**Comment by clovermye** [comment]
Same problem, need help

**Comment by Thiry1** [comment]
hmm.... I can't reproduce this issue.
So Please provide your environment.
ex)
- os version
- node version
- npm version
